### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by wildintellect** [wildintellect/system_setup#5]
Install NVM.

- should that include a Node default version (10.x to match AWS right now)?

**Comment by wildintellect** [comment]
https://github.com/nvm-sh/nvm

```
- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
```
